version: '3.7'

services:

  server1:
    image: docker.io/library/consul:1.12.3
    container_name: consul-server1
    hostname: consul-server1
    restart: always
    volumes:
      - ./server1.hcl:/consul/config/server.hcl:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    dns:
      - 10.5.0.2
      - 1.1.1.1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    command: agent -config-file=/consul/config/server.hcl -bootstrap-expect 3

  server2:
    image: docker.io/library/consul:1.12.3
    container_name: consul-server2
    hostname: consul-server2
    restart: always
    volumes:
      - ./server2.hcl:/consul/config/server.hcl:ro
    ports:
      - "8501:8500"
      - "8601:8600/tcp"
      - "8601:8600/udp"
    dns:
      - 10.5.0.2
      - 1.1.1.1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    command: agent -config-file=/consul/config/server.hcl -bootstrap-expect 3

  server3:
    image: docker.io/library/consul:1.12.3
    container_name: consul-server3
    hostname: consul-server3
    restart: always
    volumes:
      - ./server3.hcl:/consul/config/server.hcl:ro
    ports:
      - "8502:8500"
      - "8602:8600/tcp"
      - "8602:8600/udp"
    dns:
      - 10.5.0.2
      - 1.1.1.1
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    command: agent -config-file=/consul/config/server.hcl -bootstrap-expect 3

  currency-client1:
    build:
      context: ./services/currency
      dockerfile: Dockerfile
    image: currencyclient
    container_name: currency-client1
    hostname: currency-client1
    restart: always
    ports:
      - "8080:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    dns:
      - 10.5.0.2
      - 1.1.1.1

  currency-client2:
    image: currencyclient
    container_name: currency-client2
    hostname: currency-client2
    restart: always
    ports:
      - "8081:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    dns:
      - 10.5.0.2
      - 1.1.1.1
  quotes-client1:
    build:
      context: ./services/quotes
      dockerfile: Dockerfile
    image: quotesclient
    container_name: quotes-client1
    hostname: quotes-client1
    restart: always
    ports:
      - "8082:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    dns:
      - 10.5.0.2
      - 1.1.1.1

  quotes-client2:
    image: quotesclient
    container_name: quotes-client2
    hostname: quotes-client2
    restart: always
    ports:
      - "8083:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    dns:
      - 10.5.0.2
      - 1.1.1.1
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
